# -*- coding: utf-8 -*-
"""Web scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zLGsGYFYohwhSyvK6QaQIJQy8zYLIlS5

Web Scraping of yahoo Financial stats "https://uk.finance.yahoo.com/" by using **pandas datareader** and **yahoo_fin packages**

### Step 1) Import libraries
"""

## Import all the libraries
import pandas as pd
from pandas_datareader import data

##Now requires headers, pandas and pandas-datareader must be updated. Other libraries working with pdr might give you issues until gets updated or you modify the part of the code which retreives data.

!pip install --upgrade pandas-datareader

## Create variables for the sources
start_date = '2010-01-01'
end_date = '2020-01-01'

## Create dataframe
## name extracted from yahoo finance for Apple 
df = data.DataReader('aapl', data_source='yahoo' , start=start_date, end=end_date )

## View the data -earliest
df.head()

## View the data -latest
df.tail()

"""### 2) Yahoo_Fin open source packages to extract stock info"""

##Use yahoo_fin packages
!pip install yahoo_fin

## install requests_html packages
! pip install requests_html

#load library
from yahoo_fin import stock_info as si

#Pull data from yahoo finance
#get the live price
si.get_live_price('aapl')

#round the price
round(si.get_live_price('aapl'))

#round the price with one decimal
round(si.get_live_price('aapl'), 0)

#Extract income statement
si.get_income_statement('aapl', yearly=True)

##Extract analyst info
si.get_analysts_info('aapl')

## extract dividens info
si.get_dividends('aapl', start_date=start_date, end_date=end_date)

## create a dtaframe for visualisation
df = si.get_dividends('aapl', start_date=start_date, end_date=end_date)

##plot chart
df['dividend'].plot(kind='line', figsize=(10,6))

## Extract holders info
si.get_holders('aapl')